[pytest]
DJANGO_SETTINGS_MODULE = main.settings.test
python_files = tests.py tests/__init__.py
addopts = -v -s

# Environment variables ('D:' flag implies don't override existing environment variables)
env =
    D:POSTGRES_HOST=nasia.int.ocp.ajuntament.bcn
    D:POSTGRES_PORT=30001
    D:POSTGRES_USER=postgres
    D:POSTGRES_PASSWORD=5pEH5sjP