# Generated by Django 4.1.13 on 2025-11-04 08:42

from django.db import migrations


def create_default_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    Group.objects.get_or_create(name='admin')
    Group.objects.get_or_create(name='manager')


def reverse_create_default_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    Group.objects.filter(name__in=['admin', 'manager']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_groups, reverse_create_default_groups),
    ]
