version: '3'

volumes:
  prod_postgres_data: { }
  prod_postgres_data_backups: { }

services:
  django: &django
    container_name: prod-sandbox-api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    image: prod-sandbox-django
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - ./devtools/.envs/.production-test/.django
      - ./devtools/.envs/.production-test/.django-email
      - ./devtools/.envs/.production-test/.uwsgi
      - ./devtools/.envs/.production-test/.postgres
      - ./devtools/.envs/.production-test/.redis
    ports:
      - "8000:8000"
    command: uwsgi-api

  celeryworker:
    <<: *django
    container_name: prod-sandbox-celeryworker
    image: prod-sandbox-celeryworker
    ports: [ ]
    command: celery-worker

  celerybeat:
    <<: *django
    container_name: prod-sandbox-celerybeat
    image: prod-sandbox-celerybeat
    ports: [ ]
    command: celery-beat

  postgres:
    container_name: prod-sandbox-postgres
    build:
      context: ./devtools
      dockerfile: ./compose/postgresql/Dockerfile
    image: prod-sandbox-postgres
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data
      - prod_postgres_data_backups:/backups
    env_file:
      - ./devtools/.envs/.production-test/.postgres
    ports:
      - "5432:5432"

  redis:
    container_name: prod-sandbox-redis
    build:
      context: ./devtools
      dockerfile: ./compose/redis/Dockerfile
    image: prod-sandbox-redis

  spa:
    container_name: prod-sandbox-spa
    build:
      context: ./spa
      dockerfile: ./compose/production-test/Dockerfile
    image: prod-sandbox-spa
    depends_on:
      - django
    ports:
      - '80:80'
