# Generated by Django 4.1.13 on 2025-10-01 20:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('question', models.TextField(verbose_name='Question')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('explanation', models.TextField(blank=True, help_text='Explanation that appears after the question has been answered.', null=True, verbose_name='Explanation')),
                ('date_activated', models.DateTimeField(help_text='Date this question will be activated.', null=True, verbose_name='Date activated')),
                ('stage_number', models.IntegerField(help_text='The stage number this question will appear in.', null=True, verbose_name='Stage number')),
                ('image', models.ImageField(null=True, upload_to='uploads/', verbose_name='Image')),
                ('is_phishing', models.BooleanField(default=False, help_text='If this question is a phishing question (has no answers and the scoring method varies', verbose_name='Is phishing?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Score')),
                ('timestamp', models.DateTimeField(help_text='Timestamp when the score reached 10', null=True)),
                ('has_reached_max', models.BooleanField(default=False, help_text='Reached max when score reached 10', verbose_name='Reached max')),
                ('is_weekly_winner', models.BooleanField(default=False, help_text='Weekly winner when score reached 10', verbose_name='Weekly winner?')),
                ('accuracy', models.FloatField(default=0, help_text='Accuracy for phishing questions', verbose_name='Accuracy')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_score', to='authentication.department', verbose_name='Department')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_score', to='game.gamequestion', verbose_name='Question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('is_correct', models.BooleanField(default=False, help_text='Is the correct answer?', verbose_name='Correct?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.gamequestion', verbose_name='Question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='game.gameanswer', verbose_name='Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='game.gamequestion', verbose_name='Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
